import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'vi' | 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Complete translation dictionary
const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Common
    'common.dashboard': 'Trang chủ',
    'common.universities': 'Danh sách trường',
    'common.registrations': 'Đăng ký',
    'common.myCosts': 'Chi phí của tôi',
    'common.myProgress': 'Tiến trình của tôi',
    'common.studentMonitoring': 'Theo dõi học viên',
    'common.viewDetails': 'Xem chi tiết',
    'common.logout': 'Đăng xuất',
    'common.admin': 'Quản trị viên',
    'common.student': 'Sinh viên',
    'common.edit': 'Chỉnh sửa',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.register': 'Đăng ký',
    'common.close': 'Đóng',
    'common.loading': 'Đang tải...',
    'common.backToList': 'Quay lại danh sách',
    'common.accessLevel': 'Cấp độ truy cập:',
    'common.fullEditAccess': '✓ Quyền chỉnh sửa đầy đủ',
    'common.viewOnly': '🔒 Chỉ xem',
    'common.loggedInAs': 'Đã đăng nhập với vai trò',
    'common.email': 'Email',
    'common.actions': 'Hành động',
    
    // Login Page
    'login.title': 'Đăng nhập',
    'login.subtitle': 'Quản lý chi phí du học của bạn',
    'login.email': 'Email',
    'login.password': 'Mật khẩu',
    'login.role': 'Vai trò',
    'login.adminRole': 'Quản trị viên (Admin)',
    'login.studentRole': 'Sinh viên (Student)',
    'login.loginButton': 'Đăng nhập',
    'login.adminDescription': 'Quản lý chi phí trường đại học và đăng ký',
    'login.studentDescription': 'Xem trường đại học và theo dõi chi phí của bạn',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Tổng quan',
    'dashboard.totalUniversities': 'Tổng số trường',
    'dashboard.totalRegistrations': 'Tổng số đăng ký',
    'dashboard.avgCost': 'Chi phí trung bình',
    'dashboard.recentRegistrations': 'Đăng ký gần đây',
    'dashboard.universityName': 'Tên trường',
    'dashboard.student': 'Sinh viên',
    'dashboard.date': 'Ngày',
    'dashboard.tuitionTrends': 'Xu hướng học phí',
    'dashboard.university': 'Trường',
    'dashboard.tuition': 'Học phí',
    
    // Universities List
    'universities.title': 'Danh sách các trường đại học',
    'universities.subtitle': 'Khám phá các trường đại học hàng đầu',
    'universities.worldRanking': 'Xếp hạng thế giới',
    'universities.tuition': 'Học phí',
    'universities.totalCost': 'Tổng chi phí',
    'universities.actions': 'Hành động',
    'universities.registered': 'Đã đăng ký',
    'universities.alreadyRegistered': 'Đã đăng ký',
    
    // University Detail
    'university.overview': 'Tổng quan',
    'university.academicPrograms': 'Định hướng học thuật',
    'university.costs': 'Chi phí',
    'university.gallery': 'Thư viện ảnh',
    'university.ranking': 'Xếp hạng',
    'university.topPrograms': 'Các chương trình hàng đầu',
    'university.costBreakdown': 'Chi tiết chi phí',
    'university.generalTuition': 'Học phí chung',
    'university.visaFee': 'Phí visa',
    'university.accommodation': 'Chi phí lưu trú',
    'university.insurance': 'Bảo hiểm',
    'university.additionalFees': 'Phí bổ sung',
    'university.totalEstimated': 'Tổng ước tính',
    'university.registerSuccess': 'Đăng ký thành công!',
    'university.registerNow': 'Đăng ký ngay',
    'university.updateSuccess': 'Cập nhật thành công!',
    
    // My Costs
    'myCosts.title': 'Chi phí của tôi',
    'myCosts.subtitle': 'Theo dõi chi phí du học của bạn',
    
    // Costs
    'costs.tuition': 'Học phí',
    'costs.visa': 'Phí visa',
    'costs.accommodation': 'Chi phí lưu trú',
    'costs.insurance': 'Bảo hiểm',
    'costs.totalCost': 'Tổng chi phí',
    
    // Progress Tracker
    'progress.title': 'Tiến trình đăng ký du học',
    'progress.subtitle': 'Theo dõi tiến trình đăng ký của bạn',
    'progress.studentName': 'Tên sinh viên',
    'progress.targetUniversity': 'Trường mục tiêu',
    'progress.overallProgress': 'Tiến độ tổng thể',
    'progress.currentStage': 'Giai đoạn hiện tại',
    'progress.timeline': 'Lộ trình',
    'progress.viewDetails': 'Xem chi tiết',
    'progress.startDate': 'Ngày bắt đầu',
    'progress.completedDate': 'Ngày hoàn thành',
    'progress.estimatedDate': 'Ngày dự kiến',
    'progress.status': 'Trạng thái',
    'progress.statusPending': 'Chưa bắt đầu',
    'progress.statusInProgress': 'Đang thực hiện',
    'progress.statusCompleted': 'Hoàn thành',
    'progress.statusDelayed': 'Trễ hạn',
    'progress.noProgress': 'Chưa có tiến trình',
    'progress.noProgressDesc': 'Đăng ký một trường đại học để bắt đầu theo dõi tiến trình của bạn',
    'progress.viewProgress': 'Xem tiến trình',
    'progress.accessFromCosts': 'Truy cập từ trang Chi phí của tôi',
    'progress.estimatedCompletion': 'Hoàn thành dự kiến',
    'progress.notifications': 'Thông báo',
    'progress.documents': 'Tài liệu',
    'progress.uploadDocument': 'Tải lên tài liệu',
    'progress.uploaded': 'Đã tải lên',
    'progress.documentUploaded': 'Tài liệu đã được tải lên',
    'progress.notes': 'Ghi chú',
    'progress.stage': 'Giai đoạn',
    'progress.upload': 'Tải lên',
    'progress.legend': 'Chú thích',
    
    // Progress Stages
    'stage.1.title': 'Đăng ký',
    'stage.1.description': 'Đã nộp hồ sơ đăng ký du học',
    'stage.2.title': 'Học tập',
    'stage.2.description': 'Chuẩn bị học thuật và ngoại ngữ',
    'stage.3.title': 'Hoàn thành việc học',
    'stage.3.description': 'Hoàn tất các khóa học chuẩn bị',
    'stage.4.title': 'Đủ điều kiện du học',
    'stage.4.description': 'Đạt yêu cầu tuyển sinh',
    'stage.5.title': 'Đăng ký visa',
    'stage.5.description': 'Đã nộp hồ sơ xin visa',
    'stage.6.title': 'Xử lý visa',
    'stage.6.description': 'Visa đang được xử lý',
    'stage.7.title': 'Nhận visa',
    'stage.7.description': 'Đã nhận được visa du học',
    'stage.8.title': 'Đi du học',
    'stage.8.description': 'Khởi hành đến trường',
    
    // Registrations
    'registrations.title': 'Quản lý đăng ký',
    'registrations.subtitle': 'Theo dõi tất cả đăng ký sinh viên',
    'registrations.totalCount': 'Tổng số đăng ký',
    'registrations.studentEmail': 'Email sinh viên',
    'registrations.registrationDate': 'Ngày đăng ký',
    'registrations.noRegistrations': 'Chưa có đăng ký nào',
    
    // Academic Programs - Harvard
    'harvard.program1.title': 'Kinh doanh & Quản lý',
    'harvard.program1.desc': 'Top 1 thế giới - Harvard Business School nổi tiếng với MBA, Leadership, và Entrepreneurship',
    'harvard.program2.title': 'Luật & Chính sách công',
    'harvard.program2.desc': 'Top 3 thế giới - Harvard Law School và Kennedy School of Government',
    'harvard.program3.title': 'Y học & Khoa học sức khỏe',
    'harvard.program3.desc': 'Top 1 thế giới - Harvard Medical School với nghiên cứu y sinh tiên tiến',
    'harvard.program4.title': 'Khoa học máy tính & AI',
    'harvard.program4.desc': 'Top 5 thế giới - Mạnh về Machine Learning, Data Science, và Robotics',
    'harvard.program5.title': 'Kinh tế & Tài chính',
    'harvard.program5.desc': 'Top 1 thế giới - Harvard Economics với giảng viên đoạt giải Nobel',
    'harvard.program6.title': 'Nghệ thuật & Nhân văn',
    'harvard.program6.desc': 'Top 3 thế giới - Chương trình Liberal Arts toàn diện và đa dạng',
    
    // Academic Programs - MIT
    'mit.program1.title': 'Khoa học máy tính & AI',
    'mit.program1.desc': 'Top 1 thế giới - Tiên phong về AI, Robotics, và Quantum Computing',
    'mit.program2.title': 'Kỹ thuật & Công nghệ',
    'mit.program2.desc': 'Top 1 thế giới - Electrical, Mechanical, Aerospace Engineering xuất sắc',
    'mit.program3.title': 'Vật lý & Khoa học vật liệu',
    'mit.program3.desc': 'Top 1 thế giới - Nghiên cứu tiên tiến về năng lượng và vật liệu mới',
    'mit.program4.title': 'Kinh tế & Data Science',
    'mit.program4.desc': 'Top 5 thế giới - MIT Sloan School và Economics Department uy tín',
    'mit.program5.title': 'Khởi nghiệp & Innovation',
    'mit.program5.desc': 'MIT Media Lab và entrepreneurship programs hàng đầu thế giới',
    'mit.program6.title': 'Kiến trúc & Quy hoạch',
    'mit.program6.desc': 'Top 3 thế giới - MIT School of Architecture and Planning',
    
    // Academic Programs - Melbourne
    'melbourne.program1.title': 'Kinh doanh & Thương mại',
    'melbourne.program1.desc': 'Top 15 thế giới - Melbourne Business School và Commerce programs uy tín',
    'melbourne.program2.title': 'Y học & Khoa học sức khỏe',
    'melbourne.program2.desc': 'Top 10 thế giới - Nghiên cứu y sinh và clinical training xuất sắc',
    'melbourne.program3.title': 'Luật & Legal Studies',
    'melbourne.program3.desc': 'Top 10 thế giới - Melbourne Law School nổi tiếng toàn cầu',
    'melbourne.program4.title': 'Công nghệ thông tin',
    'melbourne.program4.desc': 'Top 30 thế giới - Mạnh về Software Engineering, Data Science, Cybersecurity',
    'melbourne.program5.title': 'Giáo dục & Nghệ thuật',
    'melbourne.program5.desc': 'Top 5 thế giới về Education, Top 20 về Arts and Humanities',
    'melbourne.program6.title': 'Khoa học môi trường',
    'melbourne.program6.desc': 'Top 15 thế giới - Nghiên cứu môi trường và bền vững hàng đầu',
    
    // Academic Programs - Sydney
    'sydney.program1.title': 'Kiến trúc & Design',
    'sydney.program1.desc': 'Top 15 thế giới - Chương trình Architecture và Urban Design xuất sắc',
    'sydney.program2.title': 'Khoa học xã hội',
    'sydney.program2.desc': 'Top 20 thế giới - Psychology, Sociology, và Social Policy uy tín',
    'sydney.program3.title': 'Y học & Dược',
    'sydney.program3.desc': 'Top 15 thế giới - Sydney Medical School và clinical training hàng đầu',
    'sydney.program4.title': 'Kinh doanh quốc tế',
    'sydney.program4.desc': 'Top 25 thế giới - Business School với focus về Asia-Pacific',
    'sydney.program5.title': 'Khoa học tự nhiên',
    'sydney.program5.desc': 'Top 30 thế giới - Mạnh về Biology, Chemistry, Environmental Science',
    'sydney.program6.title': 'Truyền thông & Marketing',
    'sydney.program6.desc': 'Top 20 thế giới - Media & Communications programs sáng tạo',
    
    // Admin
    'admin.studentMonitoringTitle': 'Theo dõi học viên',
    'admin.studentMonitoringSubtitle': 'Quản lý tất cả học viên và tiến trình của họ',
    'admin.totalStudents': 'Tổng số học viên',
    'admin.totalRegistrations': 'Tổng đăng ký',
    'admin.totalRevenue': 'Tổng doanh thu',
    'admin.searchStudents': 'Tìm kiếm học viên...',
    'admin.studentName': 'Tên học viên',
    'admin.registeredUniversities': 'Trường đã đăng ký',
    'admin.totalCost': 'Tổng chi phí',
    'admin.progress': 'Tiến độ',
    'admin.studentDetails': 'Thông tin chi tiết học viên',
    'admin.phone': 'Số điện thoại',
    'admin.studentCosts': 'Chi phí của học viên',
    'admin.studentProgress': 'Tiến trình của học viên',
    'admin.paymentHistory': 'Lịch sử thanh toán',
    'admin.paymentPaid': 'Đã thanh toán',
    'admin.paymentPending': 'Chờ thanh toán',
    'admin.paymentOverdue': 'Quá hạn',
    'admin.progressUpdated': 'Cập nhật tiến trình thành công!',
    'admin.noStudentsFound': 'Không tìm thấy học viên nào',
  },
  en: {
    // Common
    'common.dashboard': 'Dashboard',
    'common.universities': 'Universities',
    'common.registrations': 'Registrations',
    'common.myCosts': 'My Costs',
    'common.myProgress': 'My Progress',
    'common.studentMonitoring': 'Student Monitoring',
    'common.viewDetails': 'View Details',
    'common.logout': 'Logout',
    'common.admin': 'Admin',
    'common.student': 'Student',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.register': 'Register',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.backToList': 'Back to List',
    'common.accessLevel': 'Access Level:',
    'common.fullEditAccess': '✓ Full Edit Access',
    'common.viewOnly': '🔒 View Only',
    'common.loggedInAs': 'Logged in as',
    'common.email': 'Email',
    'common.actions': 'Actions',
    
    // Login Page
    'login.title': 'Sign In',
    'login.subtitle': 'Manage your study abroad costs',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.role': 'Role',
    'login.adminRole': 'Administrator',
    'login.studentRole': 'Student',
    'login.loginButton': 'Sign In',
    'login.adminDescription': 'Manage university costs and registrations',
    'login.studentDescription': 'View universities and track your costs',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.totalUniversities': 'Total Universities',
    'dashboard.totalRegistrations': 'Total Registrations',
    'dashboard.avgCost': 'Average Cost',
    'dashboard.recentRegistrations': 'Recent Registrations',
    'dashboard.universityName': 'University',
    'dashboard.student': 'Student',
    'dashboard.date': 'Date',
    'dashboard.tuitionTrends': 'Tuition Trends',
    'dashboard.university': 'University',
    'dashboard.tuition': 'Tuition',
    
    // Universities List
    'universities.title': 'Universities List',
    'universities.subtitle': 'Explore top universities',
    'universities.worldRanking': 'World Rank',
    'universities.tuition': 'Tuition',
    'universities.totalCost': 'Total Cost',
    'universities.actions': 'Actions',
    'universities.registered': 'Registered',
    'universities.alreadyRegistered': 'Already Registered',
    
    // University Detail
    'university.overview': 'Overview',
    'university.academicPrograms': 'Academic Programs',
    'university.costs': 'Costs',
    'university.gallery': 'Gallery',
    'university.ranking': 'Ranking',
    'university.topPrograms': 'Top Programs',
    'university.costBreakdown': 'Cost Breakdown',
    'university.generalTuition': 'General Tuition',
    'university.visaFee': 'Visa Fee',
    'university.accommodation': 'Accommodation',
    'university.insurance': 'Insurance',
    'university.additionalFees': 'Additional Fees',
    'university.totalEstimated': 'Total Estimated',
    'university.registerSuccess': 'Registration successful!',
    'university.registerNow': 'Register Now',
    'university.updateSuccess': 'Update successful!',
    
    // My Costs
    'myCosts.title': 'My Costs',
    'myCosts.subtitle': 'Track your study abroad expenses',
    
    // Costs
    'costs.tuition': 'Tuition',
    'costs.visa': 'Visa Fee',
    'costs.accommodation': 'Accommodation',
    'costs.insurance': 'Insurance',
    'costs.totalCost': 'Total Cost',
    
    // Progress Tracker
    'progress.title': 'My Application Progress',
    'progress.subtitle': 'Track your study abroad application journey',
    'progress.studentName': 'Student Name',
    'progress.targetUniversity': 'Target University',
    'progress.overallProgress': 'Overall Progress',
    'progress.currentStage': 'Current Stage',
    'progress.timeline': 'Timeline',
    'progress.viewDetails': 'View Details',
    'progress.startDate': 'Start Date',
    'progress.completedDate': 'Completed Date',
    'progress.estimatedDate': 'Estimated Date',
    'progress.status': 'Status',
    'progress.statusPending': 'Pending',
    'progress.statusInProgress': 'In Progress',
    'progress.statusCompleted': 'Completed',
    'progress.statusDelayed': 'Delayed',
    'progress.noProgress': 'No Progress Yet',
    'progress.noProgressDesc': 'Register for a university to start tracking your progress',
    'progress.viewProgress': 'View Progress',
    'progress.accessFromCosts': 'Access from My Costs page',
    'progress.estimatedCompletion': 'Estimated Completion',
    'progress.notifications': 'Notifications',
    'progress.documents': 'Documents',
    'progress.uploadDocument': 'Upload Document',
    'progress.uploaded': 'Uploaded',
    'progress.documentUploaded': 'Document Uploaded',
    'progress.notes': 'Notes',
    'progress.stage': 'Stage',
    'progress.upload': 'Upload',
    'progress.legend': 'Legend',
    
    // Progress Stages
    'stage.1.title': 'Application Submitted',
    'stage.1.description': 'Study abroad application submitted',
    'stage.2.title': 'Academic Preparation',
    'stage.2.description': 'Academic and language preparation',
    'stage.3.title': 'Preparation Completed',
    'stage.3.description': 'Preparation courses completed',
    'stage.4.title': 'Study Abroad Eligible',
    'stage.4.description': 'Met admission requirements',
    'stage.5.title': 'Visa Application',
    'stage.5.description': 'Visa application submitted',
    'stage.6.title': 'Visa Processing',
    'stage.6.description': 'Visa is being processed',
    'stage.7.title': 'Visa Received',
    'stage.7.description': 'Study visa received',
    'stage.8.title': 'Departed',
    'stage.8.description': 'Departed for university',
    
    // Registrations
    'registrations.title': 'Registration Management',
    'registrations.subtitle': 'Track all student registrations',
    'registrations.totalCount': 'Total Registrations',
    'registrations.studentEmail': 'Student Email',
    'registrations.registrationDate': 'Registration Date',
    'registrations.noRegistrations': 'No registrations yet',
    
    // Academic Programs - Harvard
    'harvard.program1.title': 'Business & Management',
    'harvard.program1.desc': 'Top 1 worldwide - Harvard Business School renowned for MBA, Leadership, and Entrepreneurship',
    'harvard.program2.title': 'Law & Public Policy',
    'harvard.program2.desc': 'Top 3 worldwide - Harvard Law School and Kennedy School of Government',
    'harvard.program3.title': 'Medicine & Health Sciences',
    'harvard.program3.desc': 'Top 1 worldwide - Harvard Medical School with advanced medical research',
    'harvard.program4.title': 'Computer Science & AI',
    'harvard.program4.desc': 'Top 5 worldwide - Strong in Machine Learning, Data Science, and Robotics',
    'harvard.program5.title': 'Economics & Finance',
    'harvard.program5.desc': 'Top 1 worldwide - Harvard Economics with Nobel laureate professors',
    'harvard.program6.title': 'Arts & Humanities',
    'harvard.program6.desc': 'Top 3 worldwide - Comprehensive and diverse Liberal Arts program',
    
    // Academic Programs - MIT
    'mit.program1.title': 'Computer Science & AI',
    'mit.program1.desc': 'Top 1 worldwide - Pioneering in AI, Robotics, and Quantum Computing',
    'mit.program2.title': 'Engineering & Technology',
    'mit.program2.desc': 'Top 1 worldwide - Excellent Electrical, Mechanical, Aerospace Engineering',
    'mit.program3.title': 'Physics & Materials Science',
    'mit.program3.desc': 'Top 1 worldwide - Advanced research in energy and new materials',
    'mit.program4.title': 'Economics & Data Science',
    'mit.program4.desc': 'Top 5 worldwide - Reputable MIT Sloan School and Economics Department',
    'mit.program5.title': 'Entrepreneurship & Innovation',
    'mit.program5.desc': 'World-leading MIT Media Lab and entrepreneurship programs',
    'mit.program6.title': 'Architecture & Planning',
    'mit.program6.desc': 'Top 3 worldwide - MIT School of Architecture and Planning',
    
    // Academic Programs - Melbourne
    'melbourne.program1.title': 'Business & Commerce',
    'melbourne.program1.desc': 'Top 15 worldwide - Reputable Melbourne Business School and Commerce programs',
    'melbourne.program2.title': 'Medicine & Health Sciences',
    'melbourne.program2.desc': 'Top 10 worldwide - Excellent medical research and clinical training',
    'melbourne.program3.title': 'Law & Legal Studies',
    'melbourne.program3.desc': 'Top 10 worldwide - Globally renowned Melbourne Law School',
    'melbourne.program4.title': 'Information Technology',
    'melbourne.program4.desc': 'Top 30 worldwide - Strong in Software Engineering, Data Science, Cybersecurity',
    'melbourne.program5.title': 'Education & Arts',
    'melbourne.program5.desc': 'Top 5 worldwide in Education, Top 20 in Arts and Humanities',
    'melbourne.program6.title': 'Environmental Science',
    'melbourne.program6.desc': 'Top 15 worldwide - Leading environmental and sustainability research',
    
    // Academic Programs - Sydney
    'sydney.program1.title': 'Architecture & Design',
    'sydney.program1.desc': 'Top 15 worldwide - Excellent Architecture and Urban Design programs',
    'sydney.program2.title': 'Social Sciences',
    'sydney.program2.desc': 'Top 20 worldwide - Reputable Psychology, Sociology, and Social Policy programs',
    'sydney.program3.title': 'Medicine & Pharmacy',
    'sydney.program3.desc': 'Top 15 worldwide - Leading Sydney Medical School and clinical training',
    'sydney.program4.title': 'International Business',
    'sydney.program4.desc': 'Top 25 worldwide - Business School with focus on Asia-Pacific',
    'sydney.program5.title': 'Natural Sciences',
    'sydney.program5.desc': 'Top 30 worldwide - Strong in Biology, Chemistry, Environmental Science',
    'sydney.program6.title': 'Media & Marketing',
    'sydney.program6.desc': 'Top 20 worldwide - Creative Media & Communications programs',
    
    // Admin
    'admin.studentMonitoringTitle': 'Student Monitoring',
    'admin.studentMonitoringSubtitle': 'Manage all students and their progress',
    'admin.totalStudents': 'Total Students',
    'admin.totalRegistrations': 'Total Registrations',
    'admin.totalRevenue': 'Total Revenue',
    'admin.searchStudents': 'Search students...',
    'admin.studentName': 'Student Name',
    'admin.registeredUniversities': 'Registered Universities',
    'admin.totalCost': 'Total Cost',
    'admin.progress': 'Progress',
    'admin.studentDetails': 'Student Details',
    'admin.phone': 'Phone',
    'admin.studentCosts': 'Student Costs',
    'admin.studentProgress': 'Student Progress',
    'admin.paymentHistory': 'Payment History',
    'admin.paymentPaid': 'Paid',
    'admin.paymentPending': 'Pending',
    'admin.paymentOverdue': 'Overdue',
    'admin.progressUpdated': 'Progress updated successfully!',
    'admin.noStudentsFound': 'No students found',
  },
  ko: {
    // Common
    'common.dashboard': '대시보드',
    'common.universities': '대학 목록',
    'common.registrations': '등록',
    'common.myCosts': '내 비용',
    'common.myProgress': '내 진행 상황',
    'common.studentMonitoring': '학생 모니터링',
    'common.viewDetails': '자세히 보기',
    'common.logout': '로그아웃',
    'common.admin': '관리자',
    'common.student': '학생',
    'common.edit': '편집',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.register': '등록',
    'common.close': '닫기',
    'common.loading': '로딩 중...',
    'common.backToList': '목록으로 돌아가기',
    'common.accessLevel': '액세스 레벨:',
    'common.fullEditAccess': '✓ 전체 편집 권한',
    'common.viewOnly': '🔒 보기 전용',
    'common.loggedInAs': '로그인 역할',
    'common.email': 'Email',
    'common.actions': '작업',
    
    // Login Page
    'login.title': '로그인',
    'login.subtitle': '유학 비용 관리',
    'login.email': '이메일',
    'login.password': '비밀번호',
    'login.role': '역할',
    'login.adminRole': '관리자',
    'login.studentRole': '학생',
    'login.loginButton': '로그인',
    'login.adminDescription': '대학 비용 및 등록 관리',
    'login.studentDescription': '대학 정보 보기 및 비용 추적',
    
    // Dashboard
    'dashboard.title': '대시보드',
    'dashboard.overview': '개요',
    'dashboard.totalUniversities': '총 대학 수',
    'dashboard.totalRegistrations': '총 등록 수',
    'dashboard.avgCost': '평균 비용',
    'dashboard.recentRegistrations': '최근 등록',
    'dashboard.universityName': '대학',
    'dashboard.student': '학생',
    'dashboard.date': '날짜',
    'dashboard.tuitionTrends': '등록금 추세',
    'dashboard.university': '대학',
    'dashboard.tuition': '등록금',
    
    // Universities List
    'universities.title': '대학 목록',
    'universities.subtitle': '상위 대학 탐색',
    'universities.worldRanking': '세계 순위',
    'universities.tuition': '등록금',
    'universities.totalCost': '총 비용',
    'universities.actions': '작업',
    'universities.registered': '등록됨',
    'universities.alreadyRegistered': '이미 등록됨',
    
    // University Detail
    'university.overview': '개요',
    'university.academicPrograms': '학술 프로그램',
    'university.costs': '비용',
    'university.gallery': '갤러리',
    'university.ranking': '순위',
    'university.topPrograms': '주요 프로그램',
    'university.costBreakdown': '비용 세부내역',
    'university.generalTuition': '일반 등록금',
    'university.visaFee': '비자 수수료',
    'university.accommodation': '숙박',
    'university.insurance': '보험',
    'university.additionalFees': '추가 수수료',
    'university.totalEstimated': '총 예상 금액',
    'university.registerSuccess': '등록 성공!',
    'university.registerNow': '지금 등록',
    'university.updateSuccess': '업데이트 성공!',
    
    // My Costs
    'myCosts.title': '내 비용',
    'myCosts.subtitle': '유학 비용 추적',
    
    // Costs
    'costs.tuition': '등록금',
    'costs.visa': '비자 수수료',
    'costs.accommodation': '숙박비',
    'costs.insurance': '보험',
    'costs.totalCost': '총 비용',
    
    // Progress Tracker
    'progress.title': '내 지원 진행 상황',
    'progress.subtitle': '유학 지원 여정 추적',
    'progress.studentName': '학생 이름',
    'progress.targetUniversity': '목표 대학',
    'progress.overallProgress': '전체 진행 상황',
    'progress.currentStage': '현재 단계',
    'progress.timeline': '타임라인',
    'progress.viewDetails': '세부정보 보기',
    'progress.startDate': '시작일',
    'progress.completedDate': '완료일',
    'progress.estimatedDate': '예상일',
    'progress.status': '상태',
    'progress.statusPending': '대기 중',
    'progress.statusInProgress': '진행 중',
    'progress.statusCompleted': '완료',
    'progress.statusDelayed': '지연됨',
    'progress.noProgress': '아직 진행 상황 없음',
    'progress.noProgressDesc': '진행 상황을 추적하려면 대학에 등록하세요',
    'progress.viewProgress': '진행 상황 보기',
    'progress.accessFromCosts': '내 비용 페이지에서 액세스',
    'progress.estimatedCompletion': '예상 완료일',
    'progress.notifications': '알림',
    'progress.documents': '문서',
    'progress.uploadDocument': '문서 업로드',
    'progress.uploaded': '업로드됨',
    'progress.documentUploaded': '문서가 업로드되었습니다',
    'progress.notes': '메모',
    'progress.stage': '단계',
    'progress.upload': '업로드',
    'progress.legend': '범례',
    
    // Progress Stages
    'stage.1.title': '지원 제출',
    'stage.1.description': '유학 지원서 제출 완료',
    'stage.2.title': '학업 준비',
    'stage.2.description': '학업 및 어학 준비',
    'stage.3.title': '준비 완료',
    'stage.3.description': '준비 과정 완료',
    'stage.4.title': '유학 자격 취득',
    'stage.4.description': '입학 요건 충족',
    'stage.5.title': '비자 신청',
    'stage.5.description': '비자 신청서 제출',
    'stage.6.title': '비자 처리',
    'stage.6.description': '비자 처리 중',
    'stage.7.title': '비자 수령',
    'stage.7.description': '유학 비자 수령',
    'stage.8.title': '출국',
    'stage.8.description': '대학으로 출발',
    
    // Registrations
    'registrations.title': '등록 관리',
    'registrations.subtitle': '모든 학생 등록 추적',
    'registrations.totalCount': '총 등록 수',
    'registrations.studentEmail': '학생 이메일',
    'registrations.registrationDate': '등록일',
    'registrations.noRegistrations': '아직 등록이 없습니다',
    
    // Academic Programs - Harvard
    'harvard.program1.title': '경영 및 관리',
    'harvard.program1.desc': '세계 1위 - MBA, 리더십, 창업을 강점으로 하는 하버드 비즈니스 스크ール',
    'harvard.program2.title': '법학 및 공공정책',
    'harvard.program2.desc': '세계 3위 - 하버드 법학대학과 켄니디 정부대학',
    'harvard.program3.title': '의학 및 건강과학',
    'harvard.program3.desc': '세계 1위 - 고급 의학 연구를 수행하는 하버드 의학대학',
    'harvard.program4.title': '컴퓨터과학 및 AI',
    'harvard.program4.desc': '세계 5위 - 머신러닝, 데이터과학, 로봇공학 분야에서 강점',
    'harvard.program5.title': '경제학 및 금융',
    'harvard.program5.desc': '세계 1위 - 노벨상 수상자 교수진이 있는 하버드 경제학과',
    'harvard.program6.title': '예술 및 인문학',
    'harvard.program6.desc': '세계 3위 - 포괄적이고 다양한 자유인문학 프로그램',
    
    // Academic Programs - MIT
    'mit.program1.title': '컴퓨터과학 및 AI',
    'mit.program1.desc': '세계 1위 - AI, 로봇공학, 양자 컴퓨팅 분야에서 선두',
    'mit.program2.title': '공학 및 기술',
    'mit.program2.desc': '세계 1위 - 전기공학, 기계공학, 우주공학 분야에서 우수',
    'mit.program3.title': '물리학 및 재료과학',
    'mit.program3.desc': '세계 1위 - 에너지와 신재료 분야에서 고급 연구',
    'mit.program4.title': '경제학 및 데이터과학',
    'mit.program4.desc': '세계 5위 - 신뢰성 있는 MIT 슬로안대학과 경제학과',
    'mit.program5.title': '창업 및 혁신',
    'mit.program5.desc': '세계 최고의 MIT 미디어랩과 창업 프로그램',
    'mit.program6.title': '건축 및 계획',
    'mit.program6.desc': '세계 3위 - MIT 건축대학과 계획대학',
    
    // Academic Programs - Melbourne
    'melbourne.program1.title': '경영 및 상업',
    'melbourne.program1.desc': '세계 15위 - 유명한 멜버른 비즈니스대학과 상업 프로그램',
    'melbourne.program2.title': '의학 및 건강과학',
    'melbourne.program2.desc': '세계 10위 - 우수한 의학 연구와 임상 교육',
    'melbourne.program3.title': '법학 및 법학 연구',
    'melbourne.program3.desc': '세계 10위 - 전 세계적으로 유명한 멜버른 법학대학',
    'melbourne.program4.title': '정보기술',
    'melbourne.program4.desc': '세계 30위 - 소프트웨어공학, 데이터과학, 사이버보안 분야에서 강점',
    'melbourne.program5.title': '교육 및 예술',
    'melbourne.program5.desc': '교육 분야에서 세계 5위, 예술과 인문학 분야에서 세계 20위',
    'melbourne.program6.title': '환경과학',
    'melbourne.program6.desc': '세계 15위 - 선두 환경 및 지속가능성 연구',
    
    // Academic Programs - Sydney
    'sydney.program1.title': '건축 및 디자인',
    'sydney.program1.desc': '세계 15위 - 우수한 건축 및 도시 디자인 프로그램',
    'sydney.program2.title': '사회과학',
    'sydney.program2.desc': '세계 20위 - 신뢰성 있는 심리학, 사회학, 사회정책 프로그램',
    'sydney.program3.title': '의학 및 약학',
    'sydney.program3.desc': '세계 15위 - 선두 시드니 의학대학과 임상 교육',
    'sydney.program4.title': '국제 경영',
    'sydney.program4.desc': '세계 25위 - 아시아태평양에 초점을 맞춘 비즈니스대학',
    'sydney.program5.title': '자연과학',
    'sydney.program5.desc': '세계 30위 - 생물학, 화학, 환경과학 분야에서 강점',
    'sydney.program6.title': '미디어 및 마케팅',
    'sydney.program6.desc': '세계 20위 - 창의적인 미디어 및 커뮤니케이션 프로그램',
    
    // Admin
    'admin.studentMonitoringTitle': '학생 모니터링',
    'admin.studentMonitoringSubtitle': '모든 학생과 그들의 진행 상황 관리',
    'admin.totalStudents': '총 학생 수',
    'admin.totalRegistrations': '총 등록 수',
    'admin.totalRevenue': '총 수익',
    'admin.searchStudents': '학생 검색...',
    'admin.studentName': '학생 이름',
    'admin.registeredUniversities': '등록된 대학',
    'admin.totalCost': '총 비용',
    'admin.progress': '진행 상황',
    'admin.studentDetails': '학생 상세 정보',
    'admin.phone': '전화번호',
    'admin.studentCosts': '학생 비용',
    'admin.studentProgress': '학생 진행 상황',
    'admin.paymentHistory': '결제 내역',
    'admin.paymentPaid': '결제 완료',
    'admin.paymentPending': '결제 대기 중',
    'admin.paymentOverdue': '연체',
    'admin.progressUpdated': '진행 상황 업데이트 성공!',
    'admin.noStudentsFound': '학생이 없습니다',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}